#!/system/bin/sh

cp BootImages/wlan-bfs.ko ./system/lib/modules/wlan.ko

cp BootImages/BFS-NoRHack.img ./boot.img
zip add -r WGBuildY-BFSNoRHack.zip system
zip add -r WGBuildY-BFSNoRHack.zip data
zip add -r WGBuildY-BFSNoRHack.zip META-INF
zip add WGBuildY-BFSNoRHack.zip boot.img
signzip WGBuildY-BFSNoRHack.zip &

cp BootImages/BFS-RHack.img ./boot.img
zip add -r WGBuildY-BFSRHack.zip system
zip add -r WGBuildY-BFSRHack.zip data
zip add -r WGBuildY-BFSRHack.zip META-INF
zip add WGBuildY-BFSRHack.zip boot.img
signzip WGBuildY-BFSRHack.zip &

cp BootImages/wlan-cfs.ko ./system/lib/modules/wlan.ko

cp BootImages/CFS-RHack.img ./boot.img
zip add -r WGBuildY-CFSRHack.zip system
zip add -r WGBuildY-CFSRHack.zip data
zip add -r WGBuildY-CFSRHack.zip META-INF
zip add WGBuildY-CFSRHack.zip boot.img
signzip WGBuildY-CFSRHack.zip &

cp BootImages/CFS-NoRHack.img ./boot.img
zip add -r WGBuildY-CFSNoRHack.zip system
zip add -r WGBuildY-CFSNoRHack.zip data
zip add -r WGBuildY-CFSNoRHack.zip META-INF
zip add WGBuildY-CFSNoRHack.zip boot.img
signzip WGBuildY-CFSNoRHack.zip
